#!/bin/bash

set -e

echo "Installing tfvm..."
pushd /tmp > /dev/null

if [ ! -d $HOME/.terraforms ]; then
    mkdir $HOME/.terraforms
fi

curl -LO https://raw.githubusercontent.com/aldiamond/tfvm/main/tfvm

if [ ! -d $HOME/bin ]; then
    mkdir $HOME/bin
fi

mv ./tfvm $HOME/bin
chmod +x $HOME/bin/tfvm
popd > /dev/null

echo "Done. Make sure $HOME/bin is on your path."
