#!/bin/bash

set -e

echo "Installing tfvm..."

if [ ! -d $HOME/.terraforms ]; then
    mkdir $HOME/.terraforms
fi

if [ ! -d $HOME/bin ]; then
    mkdir $HOME/bin
fi

if [ -f $HOME/bin/tfvm ]; then
    rm $HOME/bin/tfvm
fi

pushd $HOME/bin > /dev/null
curl -O https://raw.githubusercontent.com/aldiamond/tfvm/main/tfvm
chmod +x ./tfvm
popd > /dev/null

echo "Done."
echo "Make sure $HOME/bin is on your path."
